### ISSUE TITLE
Menu styling

### ISSUE THREAD

**Issue by boldingd** [typedrat/renaissance#2]
I've been fucking around with menu styling, but I've only gone so far because I don't want to break your templating and styling (and I don't completely understand how it works).
I set it to have absolute positioning so it will scroll, but I don't know if there wouldn't be some much better solution that would involve moving the menu around in the template.

**Comment by crutchcorn** [comment]
I will be fixing the styling by using `sticky` position and moving around some of the items, as well as making it more a11y friendly (already started)

**Comment by boldingd** [comment]
rad thanks!
